In [157]:
import numpy as np
import pandas as pd
import os
from sklearn.metrics.pairwise import cosine_distances, manhattan_distances

In [158]:
#model_dir = '/neurospin/dico/jlaval/Output/SC-sylv_right/PreV1_dim32'
model_dir = '/neurospin/dico/jlaval/Output/SC-sylv_right_for_interruption/15-59-58_59'

In [159]:
ukb_embs = pd.read_csv(os.path.join(model_dir, 'ukb40_random_embeddings/full_embeddings.csv')) # use UKB here
ukb_embs = ukb_embs.drop_duplicates(subset='ID', keep='first')
ukb_embs = ukb_embs.reset_index()

In [160]:
hcp_embs = pd.read_csv(os.path.join(model_dir, 'hcp_isomap_random_embeddings/full_embeddings.csv')) # use UKB here
hcp_embs = hcp_embs.drop_duplicates(subset='ID', keep='first')
hcp_embs = hcp_embs.reset_index()

In [161]:
interrupted_subs_T_shape = [510225, 199251, 140319, 138231]
interrupted_subs_no_T = [111009, 159946, 212419]

In [162]:
interrupted_subs_T_shape_embs = hcp_embs.loc[hcp_embs['ID'].isin(interrupted_subs_T_shape)]

In [163]:
interrupted_subs_T_shape_embs

,index,ID,dim1,dim2,dim3,dim4,dim5,dim6,dim7,dim8,...,dim23,dim24,dim25,dim26,dim27,dim28,dim29,dim30,dim31,dim32
199,199,138231,35.143204,21.736640,50.563805,-58.332460,25.022740,-40.352670,-14.456592,25.593481,...,-16.926775,-84.223890,-71.789360,29.275661,-17.999004,-39.119490,54.965263,5.241222,-49.104156,11.170620
208,208,140319,10.843114,41.476140,-33.242897,-54.835682,66.737870,-35.477043,-0.556232,14.023273,...,-61.783443,-67.605965,-20.960209,-5.303459,-28.451694,12.511851,57.862660,-8.947341,-35.536285,-25.325644
497,497,199251,27.841805,20.341343,-19.323671,-33.275272,68.398530,21.942244,31.510630,-9.567499,...,-32.596570,-115.107420,-99.278410,-12.686921,-49.507350,12.269538,27.063543,19.159418,9.604701,16.680887
763,763,510225,-25.242512,1.385895,47.128900,-13.501973,-10.351349,4.856860,10.315084,45.292507,...,3.310308,-20.065735,-14.485325,-54.839355,-12.451588,49.612390,54.195260,15.109156,-0.639479,45.339005

In [164]:
ukb_embs

,index,ID,dim1,dim2,dim3,dim4,dim5,dim6,dim7,dim8,...,dim23,dim24,dim25,dim26,dim27,dim28,dim29,dim30,dim31,dim32
0,0,sub-1000021,-112.659070,-45.923466,-1.842014,9.182813,30.051762,0.629122,-29.262321,15.732970,...,-23.877165,1.681699,20.747158,13.360238,23.191158,-9.102081,58.032448,14.267268,-9.661504,3.165399
1,1,sub-1000325,-19.831196,-19.109879,-55.237330,45.823456,61.067284,47.062490,-55.705208,-18.663246,...,-63.431046,-9.044285,5.561169,-47.534492,-29.338890,93.803670,-49.210842,-57.053234,-19.292934,5.213527
2,2,sub-1000458,-52.283962,2.368705,90.212530,-1.812664,-25.652490,-47.504433,22.385695,41.373280,...,17.214844,-12.941165,-32.842155,56.245327,-22.670979,-92.841420,44.503870,10.788336,8.162516,-0.032669
3,3,sub-1000575,14.816099,-61.811794,60.764004,-81.982620,-2.237458,-8.795115,-6.039917,16.725626,...,-14.961239,-19.009295,17.984829,-3.356141,76.374985,-54.867474,35.030014,4.556143,-30.694813,15.767738
4,4,sub-1000606,8.807077,35.463608,-53.718777,-29.537241,95.370540,-23.022720,-42.216183,6.091410,...,-57.806435,-43.745506,0.921822,46.867798,-26.855663,-25.524635,74.196930,44.282738,11.689947,-18.314514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42428,42428,sub-6023847,24.624659,-37.997940,5.031094,33.242832,21.888548,-1.941993,-24.456573,-66.315280,...,36.257225,13.688633,-5.704292,83.542030,19.412445,-75.104430,-32.367935,46.132202,22.066818,49.466175
42429,42429,sub-6024038,8.737987,-49.698410,17.657118,-42.216460,35.671410,-10.701428,36.563324,-8.707880,...,-14.178296,10.580711,-13.835815,49.277030,62.926290,-95.413734,35.379150,27.093573,13.784188,23.694271
42430,42430,sub-6024150,-78.592255,-24.277514,-22.581480,30.233906,28.560513,22.462852,-25.930727,-7.965586,...,-31.833523,-32.889286,17.673336,20.283840,16.435514,-38.819923,22.445960,0.181514,8.159156,-9.912802
42431,42431,sub-6024379,16.563742,-12.643359,89.527330,62.088192,-59.946390,-30.660759,-26.701412,-5.584861,...,75.874440,-7.105612,55.671090,19.628744,-0.402976,-57.989110,-14.457875,16.407870,-1.339053,12.455105
42432,42432,sub-6024754,27.438166,5.320234,76.922280,-18.710447,-12.574075,-69.233440,-12.061549,1.460843,...,-23.365940,-13.466087,-16.726986,55.776806,28.745370,-74.857430,28.017424,-3.552283,-28.086136,-32.436700

In [165]:
dims = [f'dim{k}' for k in range(1,33)]
ukb_data = ukb_embs[dims]
interrupted_subs_T_shape_data = interrupted_subs_T_shape_embs[dims]
nn_ukb_T_shape = cosine_distances(ukb_data, interrupted_subs_T_shape_data)

In [166]:
dist_to_T_shape = pd.DataFrame(data=nn_ukb_T_shape, columns=['Dist_to_sub0', 'Dist_to_sub1', 'Dist_to_sub2', 'Dist_to_sub3'], index=ukb_embs.ID)

In [168]:
dist_to_T_shape.sort_values(by='Dist_to_sub2').index.tolist()[:25]

'sub-2347505'

In [34]:
interrupted_ukb = dist_to_T_shape.sort_values(by='Dist_to_sub1').index.tolist()[12]
print(interrupted_ukb)

sub-1500568

In [36]:
interrupted_ukb_emb = ukb_embs.loc[ukb_embs['ID']==interrupted_ukb][dims]

In [59]:
# repeat cosine dist
nn_ukb_T_shape_ukb = manhattan_distances(ukb_data, interrupted_ukb_emb)
#nn_ukb_T_shape_ukb = cosine_distances(ukb_data, interrupted_ukb_emb)

In [60]:
dist_to_T_shape_ukb = pd.DataFrame(data=nn_ukb_T_shape_ukb, columns=['Dist_to_interrupted_ukb'], index=ukb_embs.ID)

In [61]:
dist_to_T_shape_ukb.sort_values(by='Dist_to_interrupted_ukb').index.tolist()[0:25]

['sub-1500568',
 'sub-3727234',
 'sub-4398441',
 'sub-3797761',
 'sub-2017425',
 'sub-2424796',
 'sub-3541091',
 'sub-5014578',
 'sub-4265497',
 'sub-5493039',
 'sub-3112169',
 'sub-2818128',
 'sub-3596734',
 'sub-4010460',
 'sub-4782103',
 'sub-5541614',
 'sub-4087883',
 'sub-2281993',
 'sub-4363052',
 'sub-3055966',
 'sub-4705274',
 'sub-5793840',
 'sub-4774820',
 'sub-1005443',
 'sub-2872848']

In [62]:
## other type of interruption
interrupted_subs_no_T_embs = hcp_embs.loc[hcp_embs['ID'].isin(interrupted_subs_no_T)]

In [63]:
interrupted_subs_no_T_embs

,index,ID,dim1,dim2,dim3,dim4,dim5,dim6,dim7,dim8,...,dim23,dim24,dim25,dim26,dim27,dim28,dim29,dim30,dim31,dim32
51,51,111009,3.442637,7.372863,-2.238017,-5.402393,5.132096,0.025063,8.777216,-2.981350,...,-1.935449,-0.025032,1.974425,2.800797,2.144077,-3.369983,2.588829,6.869331,1.984377,-4.854259
311,311,159946,-3.434164,6.418659,-1.219328,-7.696003,-6.126269,4.646617,2.188042,-1.556383,...,7.258718,-1.070482,1.621285,-6.805920,-0.967334,4.730247,-0.266848,-2.592735,-4.734297,-4.806720
567,567,212419,6.468065,7.956273,2.348637,1.499016,0.331806,0.597987,3.886087,-0.344866,...,1.669386,2.334049,4.338652,3.749852,1.867897,-2.607504,0.465024,1.597991,0.964162,-2.133065

In [64]:
dims = [f'dim{k}' for k in range(1,33)]
nn_ukb_no_T = cosine_distances(ukb_data, interrupted_subs_no_T_embs[dims])

In [67]:
dist_to_no_T_ukb = pd.DataFrame(data=nn_ukb_no_T, columns=['Dist_to_no_T_0', 'Dist_to_no_T_1', 'Dist_to_no_T_2'], index=ukb_embs.ID)

In [72]:
dist_to_no_T_ukb.sort_values(by='Dist_to_no_T_2').index.to_list()[:25]

['sub-1260315',
 'sub-3035833',
 'sub-1878836',
 'sub-1112909',
 'sub-3686199',
 'sub-1587851',
 'sub-4483767',
 'sub-2900221',
 'sub-1969524',
 'sub-4574485',
 'sub-4322036',
 'sub-2034993',
 'sub-2679745',
 'sub-4940014',
 'sub-3989166',
 'sub-3844475',
 'sub-1209222',
 'sub-5895008',
 'sub-4071471',
 'sub-4306627',
 'sub-5697303',
 'sub-3403935',
 'sub-5327177',
 'sub-3095163',
 'sub-5162195']

In [414]:
interrupted_subjects=['sub-5315648', 'sub-1500568', 'sub-3429392', 'sub-1376904', 'sub-2863742', 'sub-5569356', 'sub-2762943',
                      'sub-5739487', 'sub-1358401', 'sub-3492298', 'sub-3868176', 'sub-2570335', 'sub-4710606', 'sub-1820397',
                      'sub-1939418', 'sub-2239593', 'sub-3258249', 'sub-2775840', 'sub-1499791', 'sub-2347505', 'sub-5492484',
                      'sub-1698233', 'sub-4686469', 'sub-4906379', 'sub-2776534', 'sub-5493206', 'sub-1527779', 'sub-4397096',
                      'sub-3109923', 'sub-2115581', 'sub-2077194', 'sub-4959424', 'sub-3083655', 'sub-1649070', 'sub-2614377',
                      'sub-5062065', 'sub-4059279', 'sub-4860959', 'sub-2305535', 'sub-2425148', 'sub-2512500', 'sub-1935008',
                      'sub-4286421', 'sub-1553423', 'sub-3671430', 'sub-3253763', 'sub-1106033', 'sub-2731992', 'sub-1762726',
                      'sub-1461493', 'sub-1878869', 'sub-4153164']
print(len(interrupted_subjects))
print(np.unique(interrupted_subjects, return_counts=True))
print(len(np.unique(interrupted_subjects)))
print(np.argmax(np.unique(interrupted_subjects, return_counts=True)[1]))

52
(array(['sub-1106033', 'sub-1358401', 'sub-1376904', 'sub-1461493',
       'sub-1499791', 'sub-1500568', 'sub-1527779', 'sub-1553423',
       'sub-1649070', 'sub-1698233', 'sub-1762726', 'sub-1820397',
       'sub-1878869', 'sub-1935008', 'sub-1939418', 'sub-2077194',
       'sub-2115581', 'sub-2239593', 'sub-2305535', 'sub-2347505',
       'sub-2425148', 'sub-2512500', 'sub-2570335', 'sub-2614377',
       'sub-2731992', 'sub-2762943', 'sub-2775840', 'sub-2776534',
       'sub-2863742', 'sub-3083655', 'sub-3109923', 'sub-3253763',
       'sub-3258249', 'sub-3429392', 'sub-3492298', 'sub-3671430',
       'sub-3868176', 'sub-4059279', 'sub-4153164', 'sub-4286421',
       'sub-4397096', 'sub-4686469', 'sub-4710606', 'sub-4860959',
       'sub-4906379', 'sub-4959424', 'sub-5062065', 'sub-5315648',
       'sub-5492484', 'sub-5493206', 'sub-5569356', 'sub-5739487'],
      dtype='<U11'), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1]))
52
0

In [386]:
# almost interrupted ? Look at the graph
ambiguous_subjects=['sub-2302271', 'sub-3879862', 'sub-4430078', 'sub-5665608', 'sub-2375211', 'sub-4981201', 'sub-5247662',
                    'sub-4430078', 'sub-3432098', 'sub-2425148', 'sub-4956760', 'sub-4140783', 'sub-1190059', 'sub-4114077',
                    'sub-1776424', 'sub-4145012', 'sub-3834564', 'sub-2370167', 'sub-4889556', 'sub-4436954', 'sub-4430078',
                    'sub-2379487', 'sub-2681017', 'sub-4050231', 'sub-1856677', 'sub-5813265', 'sub-1405899', 'sub-5024939',
                    'sub-1405899', 'sub-5269741', 'sub-4504948', 'sub-5024939', 'sub-4865328', 'sub-1366715', 'sub-2046902']

In [441]:
selected = np.array(nn_subject)[[16]]
print(selected)
print(set(selected).intersection(interrupted_subjects))
print('Not yet selected')
np.array(set(selected).difference(interrupted_subjects)).astype(str)

['sub-2046902']
set()
Not yet selected

array("{np.str_('sub-2046902')}", dtype='<U24')

In [438]:
#subject = 'sub-1376904'
## Look at the 50 first subs ?
#subject='sub-4959424' ## has many in its neighborhood !!
#subject='sub-2614377'
subject='sub-4865328'
subject_emb = ukb_embs.loc[ukb_embs['ID']==subject][dims]
dist_to_ukb = cosine_distances(ukb_embs[dims], subject_emb)
df_dist_to_ukb = pd.DataFrame(data=dist_to_ukb, columns=['Dist'], index=ukb_embs.ID)
df_dist_to_ukb.sort_values(by='Dist', inplace=True)
nn_subject = df_dist_to_ukb.index.tolist()[0:25]
#nn_subject = df_dist_to_ukb.index.tolist()[25:50]
#nn_subject = df_dist_to_ukb.index.tolist()[50:75]

In [439]:
print(f'sample={nn_subject[0:25]}')

sample=['sub-4865328', 'sub-5566440', 'sub-5785254', 'sub-2560133', 'sub-2211582', 'sub-5686776', 'sub-4012780', 'sub-4775606', 'sub-5118293', 'sub-4668238', 'sub-3404549', 'sub-4638478', 'sub-5968202', 'sub-3123489', 'sub-3491048', 'sub-3412735', 'sub-2046902', 'sub-3976637', 'sub-2248332', 'sub-2053946', 'sub-4989642', 'sub-1845785', 'sub-5817227', 'sub-1366715', 'sub-4705440']

In [149]:
embs_interrup_subs = ukb_embs.loc[ukb_embs['ID'].isin(interrupted_subjects)]
barycenter_interrup = np.mean(embs_interrup_subs[dims], axis=0).to_numpy().reshape(1,-1)

## DISTANCE TO BARYCENTER
dist_to_ukb = cosine_distances(ukb_embs[dims], barycenter_interrup)
df_dist_to_ukb = pd.DataFrame(data=dist_to_ukb, columns=['Dist'], index=ukb_embs.ID)
df_dist_to_ukb.sort_values(by='Dist', inplace=True)
nn_subject = df_dist_to_ukb.index.tolist()[0:25]

In [156]:
## barycenter doesn't seem to work..
intersect = set(nn_subject).intersection(set(interrupted_subjects))
print(len(intersect))
set(nn_subject).difference(intersect)

5

{'sub-1249736',
 'sub-1260195',
 'sub-1462852',
 'sub-1674005',
 'sub-2141564',
 'sub-2233446',
 'sub-2262788',
 'sub-2428231',
 'sub-2592717',
 'sub-2774257',
 'sub-3141783',
 'sub-3143577',
 'sub-3268059',
 'sub-4284089',
 'sub-4888384',
 'sub-5015864',
 'sub-5565579',
 'sub-5624869',
 'sub-5850403',
 'sub-5978242'}