In [1]:
import numpy as np
import pandas as pd

In [3]:
occipital_ensemble = pd.read_csv("/neurospin/dico/agaudin/Runs/09_new_repo/Output/grid_searches/step2/occipital/ensemble_models/full_ensemble_mean_probas.csv", index_col=0)
occipital_ensemble

          labels  agg_mean1  agg_mean2
ID
10171          0   0.626814   0.373186
10193          0   0.628319   0.371681
10206          0   0.620106   0.379894
10227          0   0.632234   0.367766
10228          0   0.624126   0.375874
...          ...        ...        ...
ja110213       0   0.633310   0.366690
kk100232       0   0.629334   0.370666
ks100063       0   0.631100   0.368900
mn100399       0   0.633132   0.366868
sb100410       0   0.625444   0.374556

[1292 rows x 3 columns]

In [9]:
# predicted as schiz
pred_schiz = occipital_ensemble.sort_values(by='agg_mean2', ascending=False)[:5]
pred_no_schiz = occipital_ensemble.sort_values(by='agg_mean2', ascending=True)[:5]

print(pred_schiz)
print()
print(pred_no_schiz)
print()

print(pred_schiz.index.values)
print(pred_no_schiz.index.values)

             labels  agg_mean1  agg_mean2
ID
INVN8P57WRW       1   0.583621   0.416379
INV5FCF312N       0   0.585672   0.414328
INV937EPU3T       1   0.586295   0.413705
INVTFMLA6TH       1   0.587960   0.412040
NM1069            1   0.588220   0.411780

        labels  agg_mean1  agg_mean2
ID
11061        0   0.668639   0.331361
11142        0   0.647114   0.352886
10523        0   0.646864   0.353136
11044        0   0.646707   0.353293
CC7019       0   0.646319   0.353681
['INVN8P57WRW' 'INV5FCF312N' 'INV937EPU3T' 'INVTFMLA6TH' 'NM1069']
['11061' '11142' '10523' '11044' 'CC7019']